---
title: Laravel Basic Template
authors:
  - Jay Rogers (@jaydrogers)
  - Dan Pastori (@danpastori)
description: The official Laravel Spin template when you run `spin new laravel` from CLI.
repository: https://github.com/patipattip/spin-template-laravel-basic
issues: https://github.com/patipattip/spin-template-laravel-basic/issues