---
title: My Spin Template
authors:
  - Patipat Tippayasirin (@patipattip)
description: My Spin Template.
repository: https://github.com/patipattip/spin-template-laravel-basic
issues: https://github.com/patipattip/spin-template-laravel-basic/issues